"""Add User model

Revision ID: 64d6a7cb1ef1
Revises: 798dda1f2b97
Create Date: 2025-12-05 13:14:19.929553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d6a7cb1ef1'
down_revision = '798dda1f2b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('password_hash')

    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('provider_account_id', sa.VARCHAR(), nullable=False),
    sa.Column('access_token', sa.VARCHAR(), nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), nullable=True),
    sa.Column('expires_at', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name=op.f('_provider_unique'))
    )
    # ### end Alembic commands ###
