"""Add Game model

Revision ID: 798dda1f2b97
Revises: b3224d0c6a17
Create Date: 2025-11-26 18:28:13.391490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798dda1f2b97'
down_revision = 'b3224d0c6a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year_published', sa.String(), nullable=True),
    sa.Column('min_players', sa.String(), nullable=True),
    sa.Column('max_players', sa.String(), nullable=True),
    sa.Column('playing_time', sa.String(), nullable=True),
    sa.Column('average_weight', sa.Float(), nullable=True),
    sa.Column('designers', sa.String(), nullable=True),
    sa.Column('artists', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bgg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
